applicaciones-cas/cas

- src/main/java/org/guanzon/cas/controller/ClientMasterParameterController.java
- src/main/java/org/guanzon/cas/controller/NewCustomerController.java
- src/main/resources/org/guanzon/cas/views/ClientMasterTransactionIndividual.fxml
- src/main/resources/org/guanzon/cas/views/NewCustomer.fxml
> button controller

- nullModel_Client_Address.xml
- pom.xml
- src/main/java/org/guanzon/cas/controller/ClientMasterParameterController.java
- src/main/java/org/guanzon/cas/controller/ClientMasterTransactionCompanyController.java
- src/main/java/org/guanzon/cas/controller/ClientMasterTransactionIndividualController.java
- src/main/java/org/guanzon/cas/controller/NewCustomerController.java
- src/main/resources/org/guanzon/cas/views/ClientMasterParameter.fxml
- src/main/resources/org/guanzon/cas/views/ClientMasterTransactionCompany.fxml
> ClientMasterTransactionCompany

- nullModel_Client_Institution_Contact.xml
- src/main/java/org/guanzon/cas/controller/ClientMasterParameterController.java
- src/main/java/org/guanzon/cas/controller/ClientMasterTransactionCompanyController.java
- src/main/java/org/guanzon/cas/controller/ClientMasterTransactionIndividualController.java
- src/main/java/org/guanzon/cas/controller/NewCustomerController.java
- src/main/resources/org/guanzon/cas/views/ClientMasterParameter.fxml
- src/main/resources/org/guanzon/cas/views/ClientMasterTransactionCompany.fxml
- src/main/resources/org/guanzon/cas/views/ClientMasterTransactionIndividual.fxml
> refactor for company and standard forms

- src/main/java/org/guanzon/cas/controller/ClientMasterTransactionCompanyController.java
- src/main/java/org/guanzon/cas/controller/ClientMasterTransactionIndividualController.java
04/30/2024
company and individual forms
> refactor table click selection return to textfields

- src/main/java/org/guanzon/cas/controller/ClientMasterParameterController.java
- src/main/java/org/guanzon/cas/controller/ClientMasterTransactionCompanyController.java
- src/main/java/org/guanzon/cas/controller/ClientMasterTransactionIndividualController.java
- src/main/java/org/guanzon/cas/controller/DashboardController.java
- src/main/java/org/guanzon/cas/controller/MainScreenBGController.java
- src/main/java/org/guanzon/cas/controller/NewCustomerController.java
- src/main/java/org/guanzon/cas/controller/unloadForm.java
- src/main/resources/org/guanzon/cas/css/Tables.css
- src/main/resources/org/guanzon/cas/views/ClientMasterParameter.fxml
- src/main/resources/org/guanzon/cas/views/ClientMasterTransactionCompany.fxml
- src/main/resources/org/guanzon/cas/views/ClientMasterTransactionIndividual.fxml
- src/main/resources/org/guanzon/cas/views/MainScreenBG.fxml
- src/main/resources/org/guanzon/cas/views/NewCustomer.fxml
05/02/2024
refactor unload form from close/cancel button
refactor selection of primary address
refactor combo boxes
> refactor : individual, standard and company form

- src/main/java/org/guanzon/cas/controller/ClientMasterParameterController.java
- src/main/resources/org/guanzon/cas/views/ClientMasterParameter.fxml
refactor data selection for table address, mobile, email, social media, institutional
> refactor github conflict

- src/main/java/org/guanzon/cas/controller/DashboardController.java
- src/main/java/org/guanzon/cas/controller/FrmAccountsAccreditationController.java
- src/main/java/org/guanzon/cas/controller/FrmAccountsPayableController.java
- src/main/resources/org/guanzon/cas/views/ClientMasterParameter.fxml
- src/main/resources/org/guanzon/cas/views/ClientMasterTransactionIndividual.fxml
- src/main/resources/org/guanzon/cas/views/Dashboard.fxml
- src/main/resources/org/guanzon/cas/views/FrmAccountsAccreditation.fxml
- src/main/resources/org/guanzon/cas/views/FrmAccountsPayable.fxml
> Accounts Payable and Accreditations

- src/main/java/org/guanzon/cas/controller/ClientMasterParameterController.java
- src/main/java/org/guanzon/cas/controller/ClientMasterTransactionCompanyController.java
- src/main/java/org/guanzon/cas/controller/DashboardController.java
- src/main/java/org/guanzon/cas/controller/FrmAccountsAccreditationController.java
- src/main/java/org/guanzon/cas/controller/FrmAccountsPayableController.java
- src/main/resources/org/guanzon/cas/views/FrmAccountsAccreditation.fxml
- src/main/resources/org/guanzon/cas/views/FrmAccountsPayable.fxml
05092024
incorporating the class to UI
> REFACTOR UI for accounts payable

- pom.xml
- src/main/java/org/guanzon/cas/controller/DashboardController.java
- src/main/resources/org/guanzon/cas/views/Dashboard.fxml
5/16/2024
fix dashboard menu error
> refactor dashboard

- src/main/java/org/guanzon/cas/controller/FrmAccountsAccreditationController.java
- src/main/java/org/guanzon/cas/controller/FrmAccountsPayableController.java
- src/main/java/org/guanzon/cas/controller/FrmAccountsReceivableController.java
- src/main/java/org/guanzon/cas/model/ModelAPClientLedger.java
- src/main/java/org/guanzon/cas/model/ModelAPClientLedgers.java
- src/main/java/org/guanzon/cas/model/ModelAccredetations.java
- src/main/resources/org/guanzon/cas/css/Tables.css
- src/main/resources/org/guanzon/cas/views/FrmAccountsAccreditation.fxml
- src/main/resources/org/guanzon/cas/views/FrmAccountsPayable.fxml
- src/main/resources/org/guanzon/cas/views/FrmAccountsReceivable.fxml
05182024
retrieve update and saving of transaction
> refactor accounts accredetation

- pom.xml
- src/main/java/org/guanzon/cas/LetMeIn.java
- src/main/java/org/guanzon/cas/controller/DashboardController.java
- src/main/java/org/guanzon/cas/controller/InventoryDetailController.java
- src/main/java/org/guanzon/cas/controller/InventoryParamController.java
- src/main/java/org/guanzon/cas/controller/unloadForm.java
- src/main/resources/org/guanzon/cas/views/Dashboard.fxml
- src/main/resources/org/guanzon/cas/views/FrmAccountsPayable.fxml
- src/main/resources/org/guanzon/cas/views/FrmAccountsReceivable.fxml
- src/main/resources/org/guanzon/cas/views/InventoryDetail.fxml
- src/main/resources/org/guanzon/cas/views/InventoryLedger.fxml
- src/main/resources/org/guanzon/cas/views/InventoryParam.fxml
- src/main/resources/org/guanzon/cas/views/InventorySerial.fxml
> Inventory forms

- src/main/java/org/guanzon/cas/controller/CategoryController.java
- src/main/java/org/guanzon/cas/controller/InventoryParamController.java
- src/main/resources/org/guanzon/cas/views/InventoryDetail.fxml
- src/main/resources/org/guanzon/cas/views/InventoryParam.fxml
06/20/24
connect class to ui for
update save and browse
> inventory Param

- pom.xml
- src/main/java/org/guanzon/cas/controller/CategoryLevel3Controller.java
- src/main/java/org/guanzon/cas/controller/ClientMasterTransactionIndividualController.java
- src/main/java/org/guanzon/cas/controller/InventoryDetailController.java
- src/main/java/org/guanzon/cas/controller/InventoryLedgerController.java
- src/main/java/org/guanzon/cas/controller/InventoryParamController.java
- src/main/java/org/guanzon/cas/controller/InventorySerialController.java
- src/main/java/org/guanzon/cas/model/ModelInvLedger.java
- src/main/java/org/guanzon/cas/model/ModelInvSerial.java
- src/main/java/org/guanzon/cas/model/ModelInvSubUnit.java
- src/main/resources/org/guanzon/cas/css/overlay.css
- src/main/resources/org/guanzon/cas/views/InventoryDetail.fxml
- src/main/resources/org/guanzon/cas/views/InventoryLedger.fxml
- src/main/resources/org/guanzon/cas/views/InventoryParam.fxml
- src/main/resources/org/guanzon/cas/views/InventorySerial.fxml
> Inventory ledger and Serial

- pom.xml
> 20240823 Home

- pom.xml
- src/main/java/org/guanzon/cas/controller/BranchController.java
- src/main/java/org/guanzon/cas/controller/DashboardController.java
- src/main/java/org/guanzon/cas/controller/PO_QuotationController.java
- src/main/java/org/guanzon/cas/controller/PO_Quotation_RequestController.java
- src/main/java/org/guanzon/cas/controller/unloadForm.java
- src/main/java/org/guanzon/cas/model/ModelPOQuotationRequest.java
- src/main/resources/org/guanzon/cas/views/Branch.fxml
- src/main/resources/org/guanzon/cas/views/Dashboard.fxml
- src/main/resources/org/guanzon/cas/views/PO_Quotation.fxml
- src/main/resources/org/guanzon/cas/views/PO_Quotation_Request.fxml
ModelPOQuotationRequest.java created for table managing. Pom file slightly adjusted. unloadForm.java also updated for POQRcontroller.
> Branch/PORequest/Dashboard Controllers and UI - created/updated 

- src/main/java/org/guanzon/cas/controller/BranchController.java
- src/main/java/org/guanzon/cas/controller/DashboardController.java
- src/main/java/org/guanzon/cas/controller/PO_QuotationController.java
- src/main/java/org/guanzon/cas/model/ModelPOQuotation.java
- src/main/resources/org/guanzon/cas/views/Branch.fxml
- src/main/resources/org/guanzon/cas/views/Dashboard.fxml
- src/main/resources/org/guanzon/cas/views/PO_Quotation.fxml
PO Quotation controller, model, dashboard(to include PO Quotation) and same with branch
> PO Quotation(in progress) and Branch Module

- src/main/java/org/guanzon/cas/controller/InvRequestCancellationController.java
- src/main/java/org/guanzon/cas/controller/InvRequestCancellationGIController.java
- src/main/java/org/guanzon/cas/controller/InvRequestCancellationHistoryController.java
- src/main/java/org/guanzon/cas/controller/InvRequestCancellationHistoryGIController.java
- src/main/java/org/guanzon/cas/controller/InvRequestCancellationHistorySPController.java
- src/main/java/org/guanzon/cas/controller/InvRequestCancellationSPController.java
- src/main/java/org/guanzon/cas/controller/InvRequestHistoryController.java
- src/main/java/org/guanzon/cas/controller/InvRequestHistoryGIController.java
- src/main/java/org/guanzon/cas/controller/InvRequestHistorySPController.java
- src/main/java/org/guanzon/cas/controller/InvRequestROQController.java
- src/main/java/org/guanzon/cas/controller/InvRequestROQSPController.java
- src/main/java/org/guanzon/cas/controller/InvRequestWithoutROQController.java
- src/main/java/org/guanzon/cas/controller/InvRequestWithoutROQGIController.java
- src/main/java/org/guanzon/cas/controller/InvRequestWithoutROQSPController.java
- src/main/java/org/guanzon/cas/controller/PO_QuotationController.java
- src/main/java/org/guanzon/cas/model/ReportPrinter.java
> Refactor Stock Request Print

- src/main/java/org/guanzon/cas/controller/InvRequestHistoryController.java
- src/main/java/org/guanzon/cas/controller/InvRequestROQController.java
- src/main/java/org/guanzon/cas/controller/InvRequestROQSPController.java
- src/main/java/org/guanzon/cas/controller/InvRequestWithoutROQController.java
- src/main/java/org/guanzon/cas/controller/InvRequestWithoutROQGIController.java
- src/main/java/org/guanzon/cas/controller/InvRequestWithoutROQSPController.java
- src/main/java/org/guanzon/cas/model/ReportPrinter.java
- src/main/resources/org/guanzon/cas/views/InvRequestROQ.fxml
- src/main/resources/org/guanzon/cas/views/InvRequestROQGI.fxml
- src/main/resources/org/guanzon/cas/views/InvRequestROQSP.fxml
- src/main/resources/org/guanzon/cas/views/InvRequestWithoutROQ.fxml
- src/main/resources/org/guanzon/cas/views/InvRequestWithoutROQGI.fxml
- src/main/resources/org/guanzon/cas/views/InvRequestWithoutROQSP.fxml
10/10/23
ui approve(10/09/2024)
refactor inventory request with ROQ and without ROQ add btnapprove and btn disapprove with functionality
> Inventory Request revision

- src/main/java/org/guanzon/cas/controller/InvRequestCancellationController.java
- src/main/java/org/guanzon/cas/controller/InvRequestCancellationGIController.java
- src/main/java/org/guanzon/cas/controller/InvRequestCancellationHistoryController.java
- src/main/java/org/guanzon/cas/controller/InvRequestCancellationHistoryGIController.java
- src/main/java/org/guanzon/cas/controller/InvRequestCancellationHistorySPController.java
- src/main/java/org/guanzon/cas/controller/InvRequestCancellationSPController.java
- src/main/java/org/guanzon/cas/controller/InvRequestHistoryController.java
- src/main/java/org/guanzon/cas/controller/InvRequestHistoryGIController.java
- src/main/java/org/guanzon/cas/controller/InvRequestHistorySPController.java
- src/main/java/org/guanzon/cas/controller/InvRequestROQController.java
- src/main/java/org/guanzon/cas/controller/InvRequestROQSPController.java
- src/main/java/org/guanzon/cas/controller/InvRequestWithoutROQController.java
- src/main/java/org/guanzon/cas/controller/InvRequestWithoutROQGIController.java
- src/main/java/org/guanzon/cas/controller/InvRequestWithoutROQSPController.java
- src/main/java/org/guanzon/cas/controller/InventoryDetailController.java
- src/main/java/org/guanzon/cas/controller/InventoryParamController.java
- src/main/java/org/guanzon/cas/model/ReportPrinter.java
- src/main/resources/org/guanzon/cas/views/InvRequestROQ.fxml
- src/main/resources/org/guanzon/cas/views/InvRequestROQGI.fxml
- src/main/resources/org/guanzon/cas/views/InvRequestROQSP.fxml
- src/main/resources/org/guanzon/cas/views/InvRequestWithoutROQGI.fxml
- src/main/resources/org/guanzon/cas/views/InvRequestWithoutROQSP.fxml
10/11/2024
add oTrans.setWithUI(true);
remove clearfields on btnbrowse
enable txtfield for reference no
> Stock Request bug

- src/main/java/org/guanzon/cas/controller/DashboardController.java
- src/main/java/org/guanzon/cas/controller/InvRequestCancellationController.java
- src/main/java/org/guanzon/cas/controller/InvRequestCancellationGIController.java
- src/main/java/org/guanzon/cas/controller/InvRequestCancellationHistoryController.java
- src/main/java/org/guanzon/cas/controller/InvRequestCancellationHistoryGIController.java
- src/main/java/org/guanzon/cas/controller/InvRequestCancellationHistorySPController.java
- src/main/java/org/guanzon/cas/controller/InvRequestCancellationSPController.java
- src/main/java/org/guanzon/cas/controller/InvRequestHistoryController.java
- src/main/java/org/guanzon/cas/controller/InvRequestHistoryGIController.java
- src/main/java/org/guanzon/cas/controller/InvRequestHistorySPController.java
- src/main/java/org/guanzon/cas/controller/InvRequestROQController.java
- src/main/java/org/guanzon/cas/controller/InvRequestROQSPController.java
- src/main/java/org/guanzon/cas/controller/InvRequestWithoutROQController.java
- src/main/java/org/guanzon/cas/controller/InvRequestWithoutROQGIController.java
- src/main/java/org/guanzon/cas/controller/InvRequestWithoutROQSPController.java
10/17/2024
add watermarks on jasper report
add status parameter for jasper
> Inventory stock printing

- src/main/java/org/guanzon/cas/controller/InvRequestROQController.java
- src/main/java/org/guanzon/cas/controller/InvRequestROQSPController.java
- src/main/java/org/guanzon/cas/controller/InvRequestWithoutROQController.java
- src/main/java/org/guanzon/cas/controller/InvRequestWithoutROQSPController.java
- src/main/java/org/guanzon/cas/controller/InventoryParamController.java
10/18/2024
add sp_auto for stock request
add validation for inventory parameter
(if warehouse branch can enter or update inventory parameter)
else view only record
> inventory param and inventory request

- pom.xml
- src/main/java/org/guanzon/cas/controller/InvRequestCancellationController.java
- src/main/java/org/guanzon/cas/controller/InvRequestCancellationGIController.java
- src/main/java/org/guanzon/cas/controller/InvRequestCancellationHistoryController.java
- src/main/java/org/guanzon/cas/controller/InvRequestCancellationHistoryGIController.java
- src/main/java/org/guanzon/cas/controller/InvRequestCancellationHistorySPController.java
- src/main/java/org/guanzon/cas/controller/InvRequestCancellationSPController.java
- src/main/java/org/guanzon/cas/controller/InvRequestHistoryController.java
- src/main/java/org/guanzon/cas/controller/InvRequestHistoryGIController.java
- src/main/java/org/guanzon/cas/controller/InvRequestHistorySPController.java
- src/main/java/org/guanzon/cas/controller/InvRequestROQController.java
- src/main/java/org/guanzon/cas/controller/InvRequestROQSPController.java
- src/main/java/org/guanzon/cas/controller/InvRequestWithoutROQController.java
- src/main/java/org/guanzon/cas/controller/InvRequestWithoutROQGIController.java
- src/main/java/org/guanzon/cas/controller/InvRequestWithoutROQSPController.java
- src/main/resources/org/guanzon/cas/views/InvRequestCancellationHistoryGI.fxml
> test result updates

- pom.xml
- src/main/java/org/guanzon/cas/controller/InvRequestWithoutROQSPController.java
- src/main/java/org/guanzon/cas/controller/InventoryParamController.java
10/29/24
-fix reports save as pdf and docs
> inv request reports
